// key: custom style 키 값 / value: 원래 style key 값
export const styleTransformKey = {
  p: 'padding',
  pt: 'paddingTop',
  pb: 'paddingBottom',
  pr: 'paddingRight',
  pl: 'paddingLeft',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
  m: 'margin',
  mt: 'marginTop',
  mb: 'marginBottom',
  mr: 'marginRight',
  ml: 'marginLeft',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  w: 'width',
  h: 'height',
  minW: 'minWidth',
  minH: 'minHeight',
};

// style key
export const styleKey = {
  width: 'width',
  minWidth: 'minWidth',
  maxWidth: 'maxWidth',
  height: 'height',
  minHeight: 'minHeight',
  maxHeight: 'maxHeight',
  borderWidth: 'borderWidth',
  borderRadius: 'borderRadius',
  borderColor: 'borderColor',
  backgroundColor: 'backgroundColor',
  paddingLeft: 'paddingLeft',
  paddingRight: 'paddingRight',
  paddingTop: 'paddingTop',
  paddingBottom: 'paddingBottom',
  marginTop: 'marginTop',
  marginBottom: 'marginBottom',
  marginLeft: 'marginLeft',
  marginRight: 'marginRight',
  marginVertical: 'marginVertical',
  marginHorizontal: 'marginHorizontal',
  paddingVertical: 'paddingVertical',
  paddingHorizontal: 'paddingHorizontal',
  justifyContent: 'justifyContent',
  alignItems: 'alignItems',
  flexDirection: 'flexDirection',
  flex: 'flex',
  fontSize: 'fontSize',
  fontWeight: 'fontWeight',
  ...styleTransformKey,
};
