// key: custom style 키 값 / value: 원래 style key 값
export const styleTransformKey = {
  p: 'padding',
  pt: 'paddingTop',
  pb: 'paddingBottom',
  pr: 'paddingRight',
  pl: 'paddingLeft',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
  m: 'margin',
  mt: 'marginTop',
  mb: 'marginBottom',
  mr: 'marginRight',
  ml: 'marginLeft',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  w: 'width',
  h: 'height',
  minW: 'minWidth',
  minH: 'minHeight',
  bgColor: 'backgroundColor',
};

// style key
export const styleKey = {
  width: 'width',
  minWidth: 'minWidth',
  maxWidth: 'maxWidth',
  height: 'height',
  minHeight: 'minHeight',
  maxHeight: 'maxHeight',
  borderWidth: 'borderWidth',
  borderRadius: 'borderRadius',
  borderColor: 'borderColor',
  backgroundColor: 'backgroundColor',
  paddingLeft: 'paddingLeft',
  paddingRight: 'paddingRight',
  paddingTop: 'paddingTop',
  paddingBottom: 'paddingBottom',
  marginTop: 'marginTop',
  marginBottom: 'marginBottom',
  marginLeft: 'marginLeft',
  marginRight: 'marginRight',
  marginVertical: 'marginVertical',
  marginHorizontal: 'marginHorizontal',
  paddingVertical: 'paddingVertical',
  paddingHorizontal: 'paddingHorizontal',
  justifyContent: 'justifyContent',
  alignItems: 'alignItems',
  flexDirection: 'flexDirection',
  flex: 'flex',
  fontSize: 'fontSize',
  fontWeight: 'fontWeight',
  zIndex: 'zIndex',
  position: 'position',
  left: 'left',
  right: 'right',
  top: 'top',
  bottom: 'bottom',
  color: 'color',
  ...styleTransformKey,
};

export const uiStyle = {
  header: {
    height: 60,
  },
  tab: {
    height: 60,
  },
};

export const colors = {
  gray: {
    0: '#FFFFFF',
    10: '#F6F6F6',
    20: '#E8E9EC',
    30: '#E1E2E4',
    40: '#C6C8CD',
    50: '#9EA1A8',
    60: '#7F838C',
    70: '#5D626D',
    80: '#383E4A',
    90: '#1A1E27',
  },
  mint: {
    50: '#0DCACA',
  },
  positive: {
    30: '#002947',
    20: '#004D85',
    10: '#0070C2',
    0: '#0094FF',
    '-10': '#3DAEFF',
    '-20': '#7AC7FF',
    '-30': '#B8E1FF',
    '-40': '#E5F5FF',
  },
  negative: {
    30: '#740508',
    20: '#A5070B',
    10: '#D60A0E',
    0: '#D9D9D9',
    '-10': '#F8676A',
    '-20': '#FA989A',
    '-30': '#FDC8CA',
    '-40': '#FFEFEF',
  },
  yellow: {
    30: '#C49900',
    20: '#ECB900',
    10: '#FFCC16',
    0: '#FFE175',
    '-10': '#FFE27C',
    '-20': '#FFEEAF',
    '-30': '#FFF6D8',
    '-40': '#FFFBEC',
  },
  orange: {
    30: '#B34B00',
    20: '#C25100',
    10: '#E05E00',
    0: '#FFD53F',
    '-10': '#C6C8CD',
    '-20': '#E1E2E4',
    '-30': '#F2F2F3',
    '-40': '#FFF9F5',
  },
};
