// key: custom style 키 값 / value: 원래 style key 값
export const styleTransformKey = {
  p: 'padding',
  pt: 'paddingTop',
  pb: 'paddingBottom',
  pr: 'paddingRight',
  pl: 'paddingLeft',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
  m: 'margin',
  mt: 'marginTop',
  mb: 'marginBottom',
  mr: 'marginRight',
  ml: 'marginLeft',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  w: 'width',
  h: 'height',
  minW: 'minWidth',
  minH: 'minHeight',
  bgColor: 'backgroundColor',
};

// style key
export const styleKey = {
  width: 'width',
  minWidth: 'minWidth',
  maxWidth: 'maxWidth',
  height: 'height',
  minHeight: 'minHeight',
  maxHeight: 'maxHeight',
  borderWidth: 'borderWidth',
  borderRadius: 'borderRadius',
  borderColor: 'borderColor',
  backgroundColor: 'backgroundColor',
  paddingLeft: 'paddingLeft',
  paddingRight: 'paddingRight',
  paddingTop: 'paddingTop',
  paddingBottom: 'paddingBottom',
  marginTop: 'marginTop',
  marginBottom: 'marginBottom',
  marginLeft: 'marginLeft',
  marginRight: 'marginRight',
  marginVertical: 'marginVertical',
  marginHorizontal: 'marginHorizontal',
  paddingVertical: 'paddingVertical',
  paddingHorizontal: 'paddingHorizontal',
  justifyContent: 'justifyContent',
  alignItems: 'alignItems',
  flexDirection: 'flexDirection',
  flex: 'flex',
  fontSize: 'fontSize',
  fontWeight: 'fontWeight',
  zIndex: 'zIndex',
  position: 'position',
  left: 'left',
  right: 'right',
  top: 'top',
  bottom: 'bottom',
  ...styleTransformKey,
};

export const uiStyle = {
  header: {
    height: 60,
  },
  tab: {
    height: 60,
  },
};

export const colors = {
  gray: {
    0: '#FFFFFF',
    10: '#F6F7F7',
    20: '#ECECEE',
    30: '#E1E2E4',
    40: '#C6C8CD',
    50: '#9EA1A8',
    60: '#7F838C',
    70: '#5D626D',
    80: '#383E4A',
    90: '#1A1E27',
  },
};
